WeDoShoesCMSAdminPanel/Models/Defect.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WeDoShoesCMSAdminPanel.Models
{
    public class Defect
    {
        [JsonProperty(PropertyName = "id", NullValueHandling = NullValueHandling.Ignore)]
        public int Id { get; set; }
        [JsonProperty(PropertyName = "name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }
    }
}

WeDoShoesCMSAdminPanel/Controllers/DefectController.cs
using NLog;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using WeDoShoesCMSAdminPanel.Filter;
using WeDoShoesCMSAdminPanel.Services;
using WeDoShoesCMSAdminPanel.ViewModel;

namespace WeDoShoesCMSAdminPanel.Controllers
{
    [AuthorizeFilter]
    public class DefectController : Controller
    {
        private readonly DefectService _defectService;
        private readonly Logger _logger;
        public DefectController()
        {
            _defectService = new DefectService();
            _logger = LogManager.GetCurrentClassLogger();
        }
        // GET: Defect
        public ActionResult Index()
        {
            try
            {
                List<DefectView> listDefectView = _defectService.ListDefectView();
                return View(listDefectView);
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                return View("Error");
            }
        }

        // GET: Defect/Details/5
        public ActionResult Details(int id)
        {
            try
            {
                DefectView defect = _defectService.DefectById(id);
                return View(defect);
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                return View("Error");
            }
        }

        // GET: Defect/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Defect/Create
        [HttpPost]
        public ActionResult Create(DefectView request)
        {
            if (!ModelState.IsValid)
                return View();
            try
            {
                bool isCreated = _defectService.CreateDefect(request);
                if (isCreated)
                    return RedirectToAction("Index");
                return View("Error");
            }
            catch
            {
                return View("Error");
            }
        }

        // GET: Defect/Edit/5
        public ActionResult Edit(int id)
        {
            try
            {
                DefectView defect = _defectService.DefectById(id);
                return View(defect);
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                return View("Error");
            }
        }

        // POST: Defect/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, DefectView request)
        {
            if (!ModelState.IsValid)
                return View(request);
            try
            {
                bool isUpdated = _defectService.UpdateDefect(request);
                if (isUpdated)
                    return RedirectToAction("Index");
                return View("Error");
            }
            catch
            {
                return View("Error");
            }
        }

        // GET: Defect/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                DefectView defect = _defectService.DefectById(id);
                return View(defect);
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                return View("Error");
            }
        }

        // POST: Defect/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, DefectView request)
        {
            try
            {
                bool isDeleted = _defectService.DeleteDefect(request);
                if (isDeleted)
                    return RedirectToAction("Index");
                return View("Error");
            }
            catch
            {
                return View("Error");
            }
        }

        // GET: Defect/Search
        public ActionResult Search()
        {
            return View();
        }

        public ActionResult SearchDefect(string Keyword)
        {
            try
            {
            List<DefectView> listDefectView = _defectService.DefectByName(Keyword);
            return PartialView("_SearchDefect", listDefectView);
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                return View("Error");
            }
        }
    }
}

WeDoShoesCMSAdminPanel/Views/Defect/Create.cshtml
@model WeDoShoesCMSAdminPanel.ViewModel.DefectView

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DefectView</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WeDoShoesCMSAdminPanel/Views/Defect/Delete.cshtml
@model WeDoShoesCMSAdminPanel.ViewModel.DefectView

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DefectView</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WeDoShoesCMSAdminPanel/Views/Defect/Details.cshtml
@model WeDoShoesCMSAdminPanel.ViewModel.DefectView

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>DefectView</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WeDoShoesCMSAdminPanel/Views/Defect/Edit.cshtml
@model WeDoShoesCMSAdminPanel.ViewModel.DefectView

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DefectView</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WeDoShoesCMSAdminPanel/Views/Defect/Index.cshtml
@model IEnumerable<WeDoShoesCMSAdminPanel.ViewModel.DefectView>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>
    @if (Model != null)
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
    }
</table>

WeDoShoesCMSAdminPanel/Views/Defect/Search.cshtml
@model WeDoShoesCMSAdminPanel.ViewModel.SearchDefectView

@{
    ViewBag.Title = "Search";
}

<h2>Search Defects</h2>
@section Scripts {
<script type="text/javascript">
    var url = '@Url.Action("SearchDefect", "Defect")';
    $('#btnDisplaySearchResults').click(function () {
        var keyWord = $('#Keyword').val();
        $('#searchResults').load(url, { keyword: keyWord });
    });
    </script>
    }
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Keyword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Keyword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Keyword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" id="btnDisplaySearchResults" value="Search" />
            </div>
        </div>
        <div id="searchResults">

        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>