WeDoShoesCMSAdminPanel/Models/Product.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WeDoShoesCMSAdminPanel.Models
{
    public class Product
    {
        [JsonProperty(PropertyName = "id", NullValueHandling = NullValueHandling.Ignore)]
        public Int32? Id { get; set; }
        [JsonProperty(PropertyName = "category_id", NullValueHandling = NullValueHandling.Ignore)]
        public Int32? CategoryId { get; set; }
        [JsonProperty(PropertyName = "name", NullValueHandling = NullValueHandling.Ignore)]
        public String Name { get; set; }
        [JsonProperty(PropertyName = "description", NullValueHandling = NullValueHandling.Ignore)]
        public String Description { get; set; }
        [JsonProperty(PropertyName = "size_types", NullValueHandling = NullValueHandling.Ignore)]
        public List<int> SizeTypes { get; set; }        
        [JsonProperty(PropertyName = "services", NullValueHandling = NullValueHandling.Ignore)]
        public List<WeDoShoesService> Services { get; set; }
        [JsonProperty(PropertyName = "brands", NullValueHandling = NullValueHandling.Ignore)]
        public List<int> Brands { get; set; }
        [JsonProperty(PropertyName = "image_url", NullValueHandling = NullValueHandling.Ignore)]
        public String ImageUrl { get; set; }

        public bool ShouldSerializeConvenienceCharges()
        {
            return (SizeTypes != null || Services != null || Brands != null);
        }
    }
}

WeDoShoesCMSAdminPanel/Controllers/ProductController.cs
using NLog;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WeDoShoesCMSAdminPanel.Filter;
using WeDoShoesCMSAdminPanel.Services;
using WeDoShoesCMSAdminPanel.ViewModel;

namespace WeDoShoesCMSAdminPanel.Controllers
{
    [AuthorizeFilter]
    [RequestFilter]
    public class ProductController : Controller
    {
        private readonly ProductService _productService;
        private readonly Logger _logger;

        public ProductController()
        {
            _productService = new ProductService();
            _logger = LogManager.GetCurrentClassLogger();
        }
        // GET: Product
        public ActionResult Index()
        {
            try
            {
                List<ProductView> productList = _productService.ListProducts(0);
                return View(productList);
            }
            catch (WebException ex)
            {
                _logger.Error(ex);
                var response = ex.Response as HttpWebResponse;
                if (response != null)
                {
                    if (response.StatusCode == HttpStatusCode.Unauthorized || response.StatusCode == HttpStatusCode.Forbidden)
                    {
                        return RedirectToAction("Logout", "Account");
                    }
                }
                return RedirectToAction("Logout", "Account");
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                return View("Error");
            }
        }

        // GET: Products 
        public ActionResult ListByCategory(int? categoryId, int? size)
        {
            try
            {
                if (size == null)
                    size = 0;
                List<ProductView> productList = _productService.GetByCategoryId(categoryId, size);
                ViewBag.categoryid = categoryId;
                return View(productList);
            }
            catch (WebException ex)
            {
                _logger.Error(ex);
                var response = ex.Response as HttpWebResponse;
                if (response != null)
                {
                    if (response.StatusCode == HttpStatusCode.Unauthorized || response.StatusCode == HttpStatusCode.Forbidden)
                    {
                        return RedirectToAction("Logout", "Account");
                    }
                }
                return RedirectToAction("Logout", "Account");
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                return View("Error");
            }
        }

        // GET: Product/Details/5
        public ActionResult Details(int id)
        {
            try
            {
                ProductView product = _productService.GetDetailsById(id);
                return View(product);
            }
            catch (WebException ex)
            {
                _logger.Error(ex);
                var response = ex.Response as HttpWebResponse;
                if (response != null)
                {
                    if (response.StatusCode == HttpStatusCode.Unauthorized || response.StatusCode == HttpStatusCode.Forbidden)
                    {
                        return RedirectToAction("Logout", "Account");
                    }
                }
                return RedirectToAction("Logout", "Account");
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                return View("Error");
            }
        }

        // GET: Product/GetById/5
        public ActionResult GetById(int id, int categoryId)
        {
            try
            {
                ProductView product = _productService.GetDetailsById(id);
                return View(product);
            }
            catch (WebException ex)
            {
                _logger.Error(ex);
                var response = ex.Response as HttpWebResponse;
                if (response != null)
                {
                    if (response.StatusCode == HttpStatusCode.Unauthorized || response.StatusCode == HttpStatusCode.Forbidden)
                    {
                        return RedirectToAction("Logout", "Account");
                    }
                }
                return RedirectToAction("Logout", "Account");
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                return View("Error");
            }
        }

        //GET: Product/ListServiceOfProduct/5
        public ActionResult ListServiceOfProduct(int productId)
        {
            try
            {
                ProductView product = _productService.ListServiceOfProduct(productId);
                ViewBag.productId = productId;
                return PartialView("_ServicesOfAProduct", product);
            }
            catch (WebException ex)
            {
                _logger.Error(ex);
                var response = ex.Response as HttpWebResponse;
                if (response != null)
                {
                    if (response.StatusCode == HttpStatusCode.Unauthorized || response.StatusCode == HttpStatusCode.Forbidden)
                    {
                        return RedirectToAction("Logout", "Account");
                    }
                }
                return RedirectToAction("Logout", "Account");
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                return View("Error");
            }
        }

        //GET: List Brands of a product
        public ActionResult ListBrandsByProduct(int? productId, int? categoryId)
        {
            try
            {
                List<BrandsView> brands = _productService.ListBrandsOfAProduct(productId);
                ViewData["productid"] = productId;
                ViewData["categoryid"] = categoryId;
                return PartialView("_BrandsByProduct", brands);
            }
            catch (WebException ex)
            {
                _logger.Error(ex);
                var response = ex.Response as HttpWebResponse;
                if (response != null)
                {
                    if (response.StatusCode == HttpStatusCode.Unauthorized || response.StatusCode == HttpStatusCode.Forbidden)
                    {
                        return RedirectToAction("Logout", "Account");
                    }
                }
                return RedirectToAction("Logout", "Account");
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                return View("Error");
            }
        }

        //GET: Brands
        public ActionResult BrandsNotInProduct(int productId, int? categoryId)
        {
            try
            {
                ProductView listOfBrandsNotInProduct = _productService.ListOfBrandsNotInProduct(productId, categoryId);
                return View(listOfBrandsNotInProduct);
            }
            catch (WebException ex)
            {
                _logger.Error(ex);
                var response = ex.Response as HttpWebResponse;
                if (response != null)
                {
                    if (response.StatusCode == HttpStatusCode.Unauthorized || response.StatusCode == HttpStatusCode.Forbidden)
                    {
                        return RedirectToAction("Logout", "Account");
                    }
                }
                return RedirectToAction("Logout", "Account");
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                return View("Error");
            }
        }

        //Add Brand
        public ActionResult AddBrand(ProductView productView)
        {
            try
            {
                bool isAdded = _productService.AddBrandInAProduct(productView);
                if (isAdded)
                    return RedirectToAction("Details", new { id = productView.Id });
                return View("Error");
            }
            catch (WebException ex)
            {
                _logger.Error(ex);
                var response = ex.Response as HttpWebResponse;
                if (response != null)
                {
                    if (response.StatusCode == HttpStatusCode.Unauthorized || response.StatusCode == HttpStatusCode.Forbidden)
                    {
                        return RedirectToAction("Logout", "Account");
                    }
                }
                return RedirectToAction("Logout", "Account");
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                return View("Error");
            }
        }

        //Remove Brand
        public ActionResult RemoveBrand(int id, int productId)
        {
            try
            {
                bool isDeleted = _productService.RemoveBrandFromProduct(id, productId);
                if (isDeleted)
                    return RedirectToAction("Details", new { id = productId });
                return View("Error");
            }
            catch (WebException ex)
            {
                _logger.Error(ex);
                var response = ex.Response as HttpWebResponse;
                if (response != null)
                {
                    if (response.StatusCode == HttpStatusCode.Unauthorized || response.StatusCode == HttpStatusCode.Forbidden)
                    {
                        return RedirectToAction("Logout", "Account");
                    }
                }
                return RedirectToAction("Logout", "Account");
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                return View("Error");
            }
        }

        //GET: List Sizes of a product
        public ActionResult ListSizesByProduct(int productId)
        {
            try
            {

WeDoShoesCMSAdminPanel/Views/Product/BrandsNotInProduct.cshtml
@model WeDoShoesCMSAdminPanel.ViewModel.ProductView

@{
    ViewBag.Title = "Add Brand In Product";
}

<h2>Add Brand In Product</h2>

@using (Html.BeginForm("AddBrand", "Product", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.CategoryId)
        <div class="form-group">
            @Html.LabelFor(x => x.SelectedBrandIds, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBoxFor(x => x.SelectedBrandIds, new SelectList(Model.ListBrandsView, "Id", "Name"), new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.SelectedBrandIds, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-default" />
            </div>
        </div>
    </div>
}

WeDoShoesCMSAdminPanel/Views/Product/Delete.cshtml
@model WeDoShoesCMSAdminPanel.ViewModel.ProductView

@{
    ViewBag.Title = "Delete Product";
}

<h2>Delete Product</h2>

<h3>Are you sure you want to delete this?</h3>
<div>    
    <hr />
    <dl class="dl-horizontal">        
        <dd>
            @Html.HiddenFor(model => model.Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>*@

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" />
        </div>
    }
</div>

WeDoShoesCMSAdminPanel/Views/Product/Details.cshtml
@model WeDoShoesCMSAdminPanel.ViewModel.ProductView

@{
    ViewBag.Title = "Product Details";
}

<h2>Product Details</h2>
@section Scripts {
    <script type="text/javascript">
        $(function () {
            $.get('@Url.Action("ListBrandsByProduct", "Product", new { productId = Model.Id, categoryId = Model.CategoryId })', function (data) {

                /* data is the pure html returned from action method, load it to your page */
                $('#partialPlaceholderForBrands').html(data);
                /* little fade in effect */
                $('#partialPlaceholderForBrands').fadeIn('slow');
            });

            @*$.get('@Url.Action("ListSizesByProduct","Product",new {productId= Model.Id})', function (data) {

                /* data is the pure html returned from action method, load it to your page */
                $('#partialPlaceholderForSizes').html(data);
                /* little fade in effect */
                $('#partialPlaceholderForSizes').fadeIn('slow');
            });*@
        });
    </script>
}
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Delete", "Delete", new { id = Model.Id })
</p><br />
<div id="partialPlaceholderForBrands" style="display:none;"></div>
@*<div id="partialPlaceholderForSizes" style="display:none;"></div>*@
<div> @{Html.RenderAction("ListServiceOfProduct", "Product", new { productId = Model.Id });} </div>

WeDoShoesCMSAdminPanel/Views/Product/EditServicePrices.cshtml
@model WeDoShoesCMSAdminPanel.ViewModel.PriceView

@{
    ViewBag.Title = "Edit Prices";
}

<h2>Edit Prices</h2>

@using (Html.BeginForm("EditServicePrices","Product",FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProductSizeType)

        <div class="form-group">
            @Html.LabelFor(model => model.LabourCost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LabourCost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LabourCost, "", new { @class = "text-danger" })
            </div>
        </div>
        @if (Model.AccessoryView.AccessoryPriceView.AccessoryCost != null)
        {
            <div class="form-group">
                @Html.LabelFor(model => model.AccessoryView.AccessoryPriceView.AccessoryCost, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.AccessoryView.AccessoryPriceView.AccessoryCost, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AccessoryView.AccessoryPriceView.AccessoryCost, "", new { @class = "text-danger" })
                </div>
            </div>
        }
        else
        {
            <div class="form-group">
                @Html.LabelFor(model => model.MaterialCost, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MaterialCost, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MaterialCost, "", new { @class = "text-danger" })
                </div>
            </div>
        }

        <div class="form-group">
            @Html.LabelFor(model => model.Profit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Profit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Profit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

WeDoShoesCMSAdminPanel/Views/Product/GetById.cshtml
@model WeDoShoesCMSAdminPanel.ViewModel.ProductView

@{
    ViewBag.Title = "Add Service";
}

<h2>Product</h2>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        @*<dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>*@
    </dl>
    @*<hr />
        <div id="partialPlaceHolderForService" style="display:none;"> </div>*@
</div>

@using (Html.BeginForm("AddService", "Product", FormMethod.Post, new { request = @Model, id = "form" }))
{
    @Html.AntiForgeryToken()

    @section Scripts {
        <script type="text/javascript">
            $('#service-list').hide();
            $(function () {
                $.getJSON('@Url.Action("SubServiceTypes", "Service")', function (result) {
                    var ddl = $('#SubServiceType');
                    ddl.empty();
                    $(result).each(function () {
                        $(document.createElement('option'))
                            .attr('value', this.Type)
                            .text(this.Type)
                            .appendTo(ddl);
                    });
                });

               
            });

            $('#SubServiceType').change(function (e) {
                $('#service-list').hide();
                var selectedValue = $(this).val();
                var ddl = $('#ListOfServicesByType');
                ddl.empty();
                if (selectedValue != "--Select--") {
                    $('#service-list').show();
                    $.getJSON('@Url.Action("ListOfServicesByType", "Product")?categoryId=' + @Model.CategoryId + "&type=" + selectedValue + "&productId=" + @Model.Id, function (result) {
                        var ddl = $('#ListOfServicesByType');
                        ddl.empty();
                        $(result).each(function () {
                            $(document.createElement('option'))
                                .attr('value', this.Id)
                                .text(this.Name)
                                .appendTo(ddl);
                        });
                    })

                    $.get('@Url.Action("PriceForSelectedSizeList", "Product")?categoryId=' + @Model.CategoryId + "&productId=" + @Model.Id + "&type=" + selectedValue, function (data) {

                        /* data is the pure html returned from action method, load it to your page */
                        $('#partialPlaceHolderForSize').html(data);
                        /* little fade in effect */
                        $('#partialPlaceHolderForSize').fadeIn('slow');
                    });
                }
                e.preventDefault();
            });


            $(document).ready(function () {
                $('#Add_Service').click(function () {
                    $("form").removeData('validator');
                    $("form").removeData('unobtrusiveValidation');
                    $.validator.unobtrusive.parse($("form"));
                });
            });
        </script>
    }
    <div class="form-horizontal">
        <hr />
        <h4>Add New Service</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.CategoryId)
        <div class="form-group">
            @Html.Label("Service Type", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ServiceView.Type, new SelectList(Enumerable.Empty<SelectListItem>()), new { @class = "form-control", id = "SubServiceType" })
            </div>
        </div>

        <div id="service-list">
            <div class="form-group">
                @Html.LabelFor(model => model.ServiceView, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.SelectedServiceId, new SelectList(Enumerable.Empty<SelectListItem>()), new { @class = "form-control", id = "ListOfServicesByType" })
                </div>
            </div>
            <hr />
            <div id="partialPlaceHolderForSize" style="display:none;"> </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Add Service" class="btn btn-default" id="Add_Service" />
                </div>
            </div>
        </div>
    </div>
}

WeDoShoesCMSAdminPanel/Views/Product/Index.cshtml
@model IEnumerable<WeDoShoesCMSAdminPanel.ViewModel.ProductView>

@{
    ViewBag.Title = "Products";
}

<h2>Products</h2>

@Html.DropDownList("Category", new SelectList(Enumerable.Empty<SelectListItem>()), new { @class = "form-control", @Id = "category-type", style = "float: right;" })

@section Scripts {
    <script type="text/javascript">
        $(function () {
            $.getJSON('@Url.Action("ListCategoryForFilter", "Category")', function (result) {
                var ddl = $('#category-type');
                ddl.empty();
                $(result).each(function () {
                    $(document.createElement('option'))
                        .attr('value', this.Id)
                        .text(this.Name)
                        .appendTo(ddl);
                });
            });
        });
        $("#category-type").change(function () {
            var url = '@Url.Action("ListByCategory", "Product", new { categoryId = "_categoryId", size = 0 })';
            window.location.href = url.replace("_categoryId", $(this).val());
        });
        var categoryId = null;
    </script>
    <script src="~/Scripts/CustomScript/wedoshoes-product.js"></script>
}
<input type="hidden" id="ajaxUrl" value='@Url.Action("LoadMoreProducts", "Product")' />
<p>
    @Html.ActionLink("Create New", "Create")
</p><br />

<table class="table" id="ProductTable">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayName("Action")
        </th>
    </tr>

    @if (Model != null)
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.ActionLink("Add Services", "GetById", new { id = item.Id, categoryId = item.CategoryId }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id })
                </td>
            </tr>
        }
    }
</table>
@if (Model != null)
{
    if (Model.Count() >= 20)
    {
        <p id="loadMore" style="text-align: center;">
            <a class="btn btn-default">
                Load More@*&raquo;*@
                <span>
                    <img id="loading" style="display: none;" src="~/Content/Images/ajax-loader.gif" />
                </span>
            </a>
        </p>
    }
}

WeDoShoesCMSAdminPanel/Views/Product/ListByCategory.cshtml
@model IEnumerable<WeDoShoesCMSAdminPanel.ViewModel.ProductView>

@{
    ViewBag.Title = "Products";
}

<h2>Products</h2>

@Html.DropDownList("Category", new SelectList(Enumerable.Empty<SelectListItem>()), new { @class = "form-control", Id = "category-type", style = "float: right;" })

@section Scripts {
    <script type="text/javascript">
        $(function () {
            $.getJSON('@Url.Action("ListCategory", "Category")', function (result) {
                var ddl = $('#category-type');
                var id = @ViewBag.categoryid;
                ddl.empty();
                $(result).each(function () {
                    $(document.createElement('option'))
                        .attr('value', this.Id)
                        .text(this.Name)
                        .appendTo(ddl);
                });
                $("#category-type").find("option").each(function () {

                    if ($(this).val() == id) {

                        $(this).prop("selected", "selected");
                    }
                });
            });
        });
        $("#category-type").change(function () {
            var url = '@Url.Action("ListByCategory", "Product", new { categoryId = "_categoryId" })';
            window.location.href = url.replace("_categoryId", $(this).val());
        });

        var categoryId = @ViewBag.categoryid;
    </script>
    <script src="~/Scripts/CustomScript/wedoshoes-product.js"></script>
}
<input type="hidden" id="ajaxUrl" value='@Url.Action("LoadMoreProducts", "Product")' />
<p>
    @Html.ActionLink("Create New", "Create", new { categoryId = ViewBag.categoryid })
</p><br />

<table class="table" id="ProductTable">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayName("Action")
        </th>
    </tr>

    @if (Model != null)
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.ActionLink("Add Services", "GetById", new { id = item.Id, categoryId = item.CategoryId }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id })
                </td>
            </tr>
        }
    }

</table>
@if (Model != null)
{
    if (Model.Count() >= 20)
    {
        <p id="loadMore" style="text-align: center;">
            <a class="btn btn-default">
                Load More@*&raquo;*@
                <span>
                    <img id="loading" style="display: none;" src="~/Content/Images/ajax-loader.gif" />
                </span>
            </a>
        </p>
    }
}

WeDoShoesCMSAdminPanel/Views/Product/View.cshtml
@model WeDoShoesCMSAdminPanel.ViewModel.ProductView
<div class="form-horizontal">
    <h4>Added Services</h4>
    <hr />
   @if (Model != null)
   {
       foreach (var item in Model.ListServiceView)
       {
           <dl class="dl-horizontal">
               <dt>
                   @Html.DisplayNameFor(modelItem => item.Name)
               </dt>

               
               <dd>
                   @Html.DisplayFor(modelItem => item.Name)
               </dd>
               <dt>
                   @Html.DisplayNameFor(modelItem => item.Description)
               </dt>

               <dd>
                   @Html.DisplayFor(modelItem => item.Description)
               </dd>      
               



           </dl>
           <table>
               @foreach (var price in item.ListPriceView)
               {
               <tr>
                   <th>
                       @Html.DisplayNameFor(modelItem => price.LabourCost)
                   </th>
                  @if (price.AccessoryView.AccessoryPriceView != null)
                  {

                   <th>
                       @Html.DisplayNameFor(modelItem => price.AccessoryView.AccessoryPriceView.AccessoryCost)
                   </th>
                  }
                  else
                  {
                   <th>
                       @Html.DisplayNameFor(modelItem => price.MaterialCost)
                   </th>
                  }
                   <th>
                       @Html.DisplayNameFor(modelItem => price.Profit) 
                   </th>
                   <th>

                   </th>
               </tr>
               }
               @foreach (var price in item.ListPriceView)
               {

                <tr>
                    <th>
                        @Html.DisplayFor(modelItem => price.LabourCost)
                    </th>
                    @if (price.AccessoryView.AccessoryPriceView != null)
                    {

                        <th>
                            @Html.DisplayFor(modelItem => price.AccessoryView.AccessoryPriceView.AccessoryCost)
                        </th>
                    }
                    else
                    {
                        <th>
                            @Html.DisplayFor(modelItem => price.MaterialCost)
                        </th>
                    }
                    <th>
                        @Html.DisplayFor(modelItem => price.Profit)
                    </th>
                    <th>
                        @Html.ActionLink("Edit", "EditService", "Service", Model, new AllowHtmlAttribute())
                    </th>
                </tr>

               }


           </table>
          
       }





   }
</div>