WeDoShoesCMSAdminPanel/Controllers/ServiceController.cs
using Newtonsoft.Json;
using NLog;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WeDoShoesCMSAdminPanel.Filter;
using WeDoShoesCMSAdminPanel.Services;
using WeDoShoesCMSAdminPanel.ViewModel;

namespace WeDoShoesCMSAdminPanel.Controllers
{
    [AuthorizeFilter]
    [RequestFilter]
    public class ServiceController : Controller
    {
        private readonly ServiceService _serviceService;
        private readonly Logger _logger;

        public ServiceController()
        {
            _serviceService = new ServiceService();
            _logger = LogManager.GetCurrentClassLogger();
        }

        # region ROOT SERVICE
        // GET: RootService
        public ActionResult Index()
        {
            try
            {
                List<ServiceView> services = _serviceService.GetAllServices();
                return View(services);
            }
            catch (WebException ex)
            {
                _logger.Error(ex);
                var response = ex.Response as HttpWebResponse;
                if (response != null)
                {
                    if (response.StatusCode == HttpStatusCode.Unauthorized || response.StatusCode == HttpStatusCode.Forbidden)
                    {
                        return RedirectToAction("Logout", "Account");
                    }
                }
                return RedirectToAction("Logout", "Account");
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                return View("Error");
            }
        }

        //GET: RootService by category Id.
        public ActionResult ListByCategory(int categoryId)
        {
            try
            {
                List<ServiceView> services = _serviceService.GetByCategoryId(categoryId);
                ViewData["categoryid"] = categoryId;
                return View(services);
            }
            catch (WebException ex)
            {
                _logger.Error(ex);
                var response = ex.Response as HttpWebResponse;
                if (response != null)
                {
                    if (response.StatusCode == HttpStatusCode.Unauthorized || response.StatusCode == HttpStatusCode.Forbidden)
                    {
                        return RedirectToAction("Logout", "Account");
                    }
                }
                return RedirectToAction("Logout", "Account");
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                return View("Error");
            }
        }

        //GET: Root service details by Id.
        public ActionResult RootServiceDetails(int id)
        {
            try
            {
                ServiceView rootService = _serviceService.RootServiceDetails(id);
                return View(rootService);
            }
            catch (WebException ex)
            {
                _logger.Error(ex);
                var response = ex.Response as HttpWebResponse;
                if (response != null)
                {
                    if (response.StatusCode == HttpStatusCode.Unauthorized || response.StatusCode == HttpStatusCode.Forbidden)
                    {
                        return RedirectToAction("Logout", "Account");
                    }
                }
                return RedirectToAction("Logout", "Account");
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                return View("Error");
            }
        }

        //GET: Root service details by Id.
        public ActionResult EditRootService(ServiceView request)
        {
            return View(request);
        }

        //POST: Edit Root service.
        [HttpPost]
        public ActionResult EditRootService(int id, ServiceView request)
        {
            try
            {
                bool isUpdated = _serviceService.UpdateRootServiceById(id, request);
                if (isUpdated)
                    return RedirectToAction("RootServiceDetails", new { id = id });
                return View("Error");
            }
            catch (WebException ex)
            {
                _logger.Error(ex);
                var response = ex.Response as HttpWebResponse;
                if (response != null)
                {
                    if (response.StatusCode == HttpStatusCode.Unauthorized || response.StatusCode == HttpStatusCode.Forbidden)
                    {
                        return RedirectToAction("Logout", "Account");
                    }
                }
                return RedirectToAction("Logout", "Account");
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                return View("Error");
            }
        }

        //Get: Root Service Processing days
        public ActionResult EditRootServiceProcessingTime(int id)
        {
            try
            {
                ServiceView rootService = _serviceService.GetRootServiceProcessingTime(id);
                return View(rootService);
            }
            catch (WebException ex)
            {
                _logger.Error(ex);
                var response = ex.Response as HttpWebResponse;
                if (response != null)
                {
                    if (response.StatusCode == HttpStatusCode.Unauthorized || response.StatusCode == HttpStatusCode.Forbidden)
                    {
                        return RedirectToAction("Logout", "Account");
                    }
                }
                return RedirectToAction("Logout", "Account");
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                return View("Error");
            }
        }

        //POST: Edit Root service.
        [HttpPost]
        public ActionResult EditRootServiceProcessingTime(int id, ServiceView request)
        {
            try
            {
                bool isUpdated = _serviceService.UpdateRootServiceProcessingTime(id, request);
                if (isUpdated)
                    return RedirectToAction("RootServiceDetails", new { id = id });
                return View("Error");
            }
            catch (WebException ex)
            {
                _logger.Error(ex);
                var response = ex.Response as HttpWebResponse;
                if (response != null)
                {
                    if (response.StatusCode == HttpStatusCode.Unauthorized || response.StatusCode == HttpStatusCode.Forbidden)
                    {
                        return RedirectToAction("Logout", "Account");
                    }
                }
                return RedirectToAction("Logout", "Account");
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                return View("Error");
            }
        }

        //Get: Root service prices
        public ActionResult EditRootServicePrices(int id)
        {
            try
            {
                ServiceView rootService = _serviceService.GetRootServiceCharges(id);
                return View(rootService);
            }
            catch (WebException ex)
            {
                _logger.Error(ex);
                var response = ex.Response as HttpWebResponse;
                if (response != null)
                {
                    if (response.StatusCode == HttpStatusCode.Unauthorized || response.StatusCode == HttpStatusCode.Forbidden)
                    {
                        return RedirectToAction("Logout", "Account");
                    }
                }
                return RedirectToAction("Logout", "Account");
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                return View("Error");
            }
        }

        //POST: Edit Root service.
        [HttpPost]
        public ActionResult EditRootServicePrices(int id, ServiceView request)
        {
            try
            {
                bool isUpdated = _serviceService.UpdateRootServiceCharges(id, request);
                if (isUpdated)
                    return RedirectToAction("RootServiceDetails", new { id = id });
                return View("Error");
            }
            catch (WebException ex)
            {
                _logger.Error(ex);
                var response = ex.Response as HttpWebResponse;
                if (response != null)
                {
                    if (response.StatusCode == HttpStatusCode.Unauthorized || response.StatusCode == HttpStatusCode.Forbidden)
                    {
                        return RedirectToAction("Logout", "Account");
                    }
                }
                return RedirectToAction("Logout", "Account");
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                return View("Error");
            }
        }

        //POST: Edit Processing Days
        [HttpPost]
        public ActionResult EditProcessingTime(int id, ServiceView request)
        {
            if (request.ProcessingTimeView.NormalProcessingDays == null || request.ProcessingTimeView.ExpressProcessingDays == null)
                return View("EditRootService", request);
            try
            {
                bool isUpdated = _serviceService.UpdateProcessingTime(id, request);
                if (isUpdated)
                    return RedirectToAction("RootServiceDetails/" + id);
                return View("Error");
            }
            catch (WebException ex)
            {
                _logger.Error(ex);
                var response = ex.Response as HttpWebResponse;
                if (response != null)
                {
                    if (response.StatusCode == HttpStatusCode.Unauthorized || response.StatusCode == HttpStatusCode.Forbidden)

WeDoShoesCMSAdminPanel/Views/Service/DeleteSubService.cshtml
@model WeDoShoesCMSAdminPanel.ViewModel.SubServiceView

@{
    ViewBag.Title = "Delete Sub-Service";
}

<h2>Delete Sub-Service</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Acronym)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Acronym)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>

    @using (Html.BeginForm(new { id = Model.Id, parentId = Model.ParentId }))
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" />
        </div>
    }
</div>

WeDoShoesCMSAdminPanel/Views/Service/EditRootServiceProcessingTime.cshtml
@model WeDoShoesCMSAdminPanel.ViewModel.ServiceView

@{
    ViewBag.Title = "Edit Processing Time";
}

<h2>Edit Processing Time</h2>

@using (Html.BeginForm("EditRootServiceProcessingTime", "Service", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.ProcessingTimeView.NormalProcessingDays, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProcessingTimeView.NormalProcessingDays, new { htmlAttributes = new { @class = "form-control" , @min = "0" } })
                @Html.ValidationMessageFor(model => model.ProcessingTimeView.NormalProcessingDays, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProcessingTimeView.ExpressProcessingDays, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProcessingTimeView.ExpressProcessingDays, new { htmlAttributes = new { @class = "form-control", @min = "0" } })
                @Html.ValidationMessageFor(model => model.ProcessingTimeView.ExpressProcessingDays, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

WeDoShoesCMSAdminPanel/Views/Service/EditService.cshtml
@model WeDoShoesCMSAdminPanel.ViewModel.ServiceView

@{
    ViewBag.Title = "Edit Service";
}

<h2>Edit Service</h2>

@using (Html.BeginForm("EditService", "Service", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @section Scripts {
    <script type="text/javascript">
        $(function () {
            $.getJSON('@Url.Action("ListSubServiceType","Service")', function (result) {
                var ddl = $('#SubServiceType');
                ddl.empty();
                $(result).each(function () {
                    $(document.createElement('option'))
                        .attr('value', this.Type)
                        .text(this.Type)
                        .appendTo(ddl);
                });
                ddl.val("@Model.Type")
            });
        });


        $('#sub-services').hide();
       
        $('#has-children').change(function () {
            if ($(this).prop("checked")) {
                $('#sub-services').hide();
                $('#sub-services').toggle("slow");

            }
            else {
                $('#sub-services').hide("slow");

            }
        });

        $(document).ready(function () {
            $('#sub').click(function () {

                $("form").removeData('validator');
                $("form").removeData('unobtrusiveValidation');
                $.validator.unobtrusive.parse($("form"));
            });
        });

        $(document).ready(function () {
            $("#btnClick").click(function () {

                $.post("/Service/AppendSubService",
                  function (response) {

                      if ($("#has-children").prop("checked")) {

                          $('#sub-services').append(response), function () {

                              //$.validator.unobtrusive.parse($(this));

                          }
                      }

                  }
                );
            });
        });

        function deleteAddress(Id) {
            Id.remove();
        }

    </script>
    }
    <div class="form-horizontal">        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.ParentId)
        @Html.HiddenFor(model => model.CategoryId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Acronym, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Acronym, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Acronym, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Type, new SelectList(Enumerable.Empty<SelectListItem>()), new { @class = "form-control", id = "SubServiceType" })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>        

        <div class="form-group">
            @Html.LabelFor(model => model.HasChildren, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.CheckBoxFor(model => model.HasChildren, new { id = "has-children" })
                    @Html.ValidationMessageFor(model => model.HasChildren, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div id="sub-services">
            <hr />
            <h2>Sub-Service</h2>
            <div class="form-group sub-service-name" id="sub-service-name">
                @Html.LabelFor(model => model.SubServiceView.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SubServiceView.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SubServiceView.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SubServiceView.Acronym, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SubServiceView.Acronym, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SubServiceView.Acronym, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group sub-service-description" id="sub-service-description">
                @Html.LabelFor(model => model.SubServiceView.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SubServiceView.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SubServiceView.Description, "", new { @class = "text-danger" })
                </div>
            </div>
            <div>
                <hr>
                <input type="button" value="Add More SubServices" id="btnClick" />
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

WeDoShoesCMSAdminPanel/Views/Service/Index.cshtml
@model IEnumerable<WeDoShoesCMSAdminPanel.ViewModel.ServiceView>

@{
    ViewBag.Title = "Root Services";
}
<h5>@Html.ActionLink("Root Services", "Index", "Service")</h5>
<h2>Root Services</h2>

@Html.DropDownList("Category", new SelectList(Enumerable.Empty<SelectListItem>()), new { @class = "form-control", @Id = "category-type", style = "float: right;" })

@section Scripts {
    <script src="~/Scripts/CustomScript/LoadMoreService.js"></script>
    <script type="text/javascript">
        $(function () {
            $.getJSON('@Url.Action("ListCategoryForFilter","Category")', function (result) {
                var ddl = $('#category-type');
                ddl.empty();
                $(result).each(function () {
                    $(document.createElement('option'))
                        .attr('value', this.Id)
                        .text(this.Name)
                        .appendTo(ddl);
                });
            });
        });
        $("#category-type").change(function () {
            var url = '@Url.Action("ListByCategory", "Service", new { categoryId = "_categoryId" })';
            window.location.href = url.replace("_categoryId", $(this).val());
        });
    </script>
}

<p>
    @Html.ActionLink("Create New", "CreateRootService")
</p><br />

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Acronym)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayName("Action")
        </th>
    </tr>

    @if (Model != null)
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Acronym)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.ActionLink("Add Service", "CreateService", new { parentId = item.Id, categoryId = item.CategoryId}, new AllowHtmlAttribute()) |
                    @Html.ActionLink("Details", "RootServiceDetails", "Service", new { id = item.Id }, new AllowHtmlAttribute())
                </td>
            </tr>
        }
    }

</table>

WeDoShoesCMSAdminPanel/Views/Service/ListByCategory.cshtml
@model IEnumerable<WeDoShoesCMSAdminPanel.ViewModel.ServiceView>

@{
    ViewBag.Title = "Root Services";
}

<h2>Root Services</h2>

@Html.DropDownList("Category", new SelectList(Enumerable.Empty<SelectListItem>()), new { @class = "form-control", @Id = "category-type", style = "float: right;" })

@section Scripts {
    <script type="text/javascript">
        $(function () {
            $.getJSON('@Url.Action("ListCategory", "Category")', function (result) {
                var ddl = $('#category-type');
                var id = @ViewData["categoryid"];
                ddl.empty();
                $(result).each(function () {
                    $(document.createElement('option'))
                        .attr('value', this.Id)
                        .text(this.Name)
                        .appendTo(ddl);
                });
                $("#category-type").find("option").each(function () {

                    if ($(this).val() == id) {

                        $(this).prop("selected", "selected");
                    }
                });
            });
        });
        $("#category-type").change(function () {
            var url = '@Url.Action("ListByCategory", "Service", new { categoryId = "_categoryId" })';
            window.location.href = url.replace("_categoryId", $(this).val());
        });
</script>
}

<p>
    @Html.ActionLink("Create New", "CreateRootService", new { categoryId = ViewData["categoryid"] })
</p><br />

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Acronym)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayName("Action")
        </th>
    </tr>

    @if (Model != null)
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Acronym)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>               
                    @Html.ActionLink("Add Service", "CreateService", item, new AllowHtmlAttribute()) |     
                    @Html.ActionLink("Details", "RootServiceDetails", "Service", new { id = item.Id }, new AllowHtmlAttribute())                    
                </td>
            </tr>
        }
    }

</table>

WeDoShoesCMSAdminPanel/Views/Service/RootServiceDetails.cshtml
@model WeDoShoesCMSAdminPanel.ViewModel.ServiceView

@{
    ViewBag.Title = "Root Service Details";
}
<h5>@Html.ActionLink("Root Services", "Index", "Service") /
     @Html.ActionLink(Model.Name, "RootServiceDetails", new { id = (int)Model.Id })</h5>
<h2>Root Service Details</h2>
@section Scripts {
    <script>
        var serviceId = @(Model.Id);
        var categoryId = @(Model.CategoryId);
    </script>
    <script src="~/Scripts/CustomScript/wedoshoes-service.js"></script>
}
<input type="hidden" id="ajaxUrl" value='@Url.Action("LoadMoreServices", "Service")' />
<div>
    <hr />
    <dl class="dl-horizontal">
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.CategoryId)
        @Html.HiddenFor(model => model.ParentId)
        @Html.HiddenFor(model => model.Type)
        @Html.HiddenFor(model => model.HasChildren)
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Acronym)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Acronym)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dd>
            @Html.ActionLink("Edit", "EditRootService", "Service", Model, new AllowHtmlAttribute()) 
        </dd>
        @if (Model.ProcessingTimeView != null)
        {
            <dt>
                @Html.DisplayNameFor(model => model.ProcessingTimeView.NormalProcessingDays)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ProcessingTimeView.NormalProcessingDays)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ProcessingTimeView.ExpressProcessingDays)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ProcessingTimeView.ExpressProcessingDays)
            </dd>
            <dd>
                @Html.ActionLink("Edit", "EditRootServiceProcessingTime", "Service", new { id = Model.Id, Model.ProcessingTimeView }, new AllowHtmlAttribute())
            </dd>
        }

        @if (Model.ConvenienceChargesView != null)
        {
            <dt>
                @Html.DisplayNameFor(model => model.ConvenienceChargesView.ConvenienceCharge)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ConvenienceChargesView.ConvenienceCharge)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ConvenienceChargesView.SingleOrderExpressProcessingCharge)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ConvenienceChargesView.SingleOrderExpressProcessingCharge)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ConvenienceChargesView.MultiOrderExpressProcessingChargePerOrder)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ConvenienceChargesView.MultiOrderExpressProcessingChargePerOrder)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ConvenienceChargesView.PackingCharge)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ConvenienceChargesView.PackingCharge)
            </dd>
            <dd>
                @Html.ActionLink("Edit", "EditRootServicePrices", "Service", new { id = Model.Id, request = Model.ConvenienceChargesView }, new AllowHtmlAttribute())
            </dd>
        }
    </dl>
</div>

<div> @{Html.RenderAction("ServicesByRoot", "Service", new { id = Model.Id, categoryId = Model.CategoryId });} </div>

WeDoShoesCMSAdminPanel/Views/Service/ServiceDetails.cshtml
@model WeDoShoesCMSAdminPanel.ViewModel.ServiceView

@{
    ViewBag.Title = "Service Details";
    string rootServiceName = ViewBag.RootServiceName;
}
<h5>
    @Html.ActionLink("Root Services", "Index", "Service") /
@Html.ActionLink(rootServiceName, "RootServiceDetails", new { id = (int)Model.ParentId }) /
@Html.ActionLink(Model.Name, "ServiceDetails", new { id = (int)Model.Id })
</h5>
<h2>Service Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Acronym)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Acronym)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        @Html.HiddenFor(model => model.ParentId)
        @Html.HiddenFor(model => model.CategoryId)
        @Html.HiddenFor(model => model.Id)
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "EditService", Model) |
    @Html.ActionLink("Delete", "DeleteService", Model, new AllowHtmlAttribute())
</p>
@if (Model.HasChildren)
{

<div>
    @{Html.RenderAction("SubServicesByService", "Service", new { parentId = Model.Id, categoryId = Model.CategoryId, type = Model.Type });
    }
</div>

}

WeDoShoesCMSAdminPanel/Views/Service/SubServiceDetails.cshtml
@model WeDoShoesCMSAdminPanel.ViewModel.SubServiceView

@{
    ViewBag.Title = "Sub-Service Details";
    int rootServiceId=(int)ViewBag.RootServiceId;
    string serviceName=ViewBag.ServiceName ;
    string rootServiceName=ViewBag.RootServiceName;
}

<h5>@Html.ActionLink("Root Services", "Index", "Service") /
     @Html.ActionLink(rootServiceName, "RootServiceDetails", new { id = (int)rootServiceId }) / 
    @Html.ActionLink(serviceName, "ServiceDetails", new { id = (int)Model.ParentId }) /
     @Html.ActionLink(Model.Name, "SubServiceDetails", new { id = (int)Model.Id })</h5>
<h2>Sub-Service Details</h2>

<div>    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Acronym)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Acronym)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>                
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "EditSubService", Model) |
    @Html.ActionLink("Delete", "DeleteSubService", Model)
</p>