WeDoShoesCMSAdminPanel/Controllers/APIController.cs
using NLog;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WeDoShoesCMSAdminPanel.Filter;
using WeDoShoesCMSAdminPanel.Services;
using WeDoShoesCMSAdminPanel.ViewModel;

namespace WeDoShoesCMSAdminPanel.Controllers
{
    [AuthorizeFilter]
    public class APIController : Controller
    {
        private readonly APIService _apiService;
        private readonly Logger _logger;

        public APIController()
        {
            _apiService = new APIService();
            _logger = LogManager.GetCurrentClassLogger();
        }
        // GET: API
        public ActionResult Index()
        {
            try
            {
                List<APIView> apiList = _apiService.ListAPI(0);
                return View(apiList);
            }
            catch (WebException ex)
            {
                _logger.Error(ex);
                var response = ex.Response as HttpWebResponse;
                if (response != null)
                {
                    if (response.StatusCode == HttpStatusCode.Unauthorized || response.StatusCode == HttpStatusCode.Forbidden)
                    {
                        return RedirectToAction("Logout", "Account");
                    }
                }
                return RedirectToAction("Logout", "Account");
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                return View("Error");
            }
        }

        [HttpPost]
        public ActionResult LoadMoreAPI(int size)
        {
            try
            {
                List<APIView> apiList = _apiService.ListAPI(size);
                if (apiList != null)
                {
                    return PartialView("_LoadMoreAPI", apiList);
                }
                return Json(apiList);
            }
            catch (WebException ex)
            {
                _logger.Error(ex);
                var response = ex.Response as HttpWebResponse;
                if (response != null)
                {
                    if (response.StatusCode == HttpStatusCode.Unauthorized || response.StatusCode == HttpStatusCode.Forbidden)
                    {
                        return RedirectToAction("Logout", "Account");
                    }
                }
                return RedirectToAction("Logout", "Account");
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                return View("Error");
            }
        }
        // GET: API/Details/5
        public ActionResult Details(int id)
        {
            try
            {
                APIView api = _apiService.APIDetails(id);
                return View(api);
            }
            catch (WebException ex)
            {
                _logger.Error(ex);
                var response = ex.Response as HttpWebResponse;
                if (response != null)
                {
                    if (response.StatusCode == HttpStatusCode.Unauthorized || response.StatusCode == HttpStatusCode.Forbidden)
                    {
                        return RedirectToAction("Logout", "Account");
                    }
                }
                return RedirectToAction("Logout", "Account");
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                return View("Error");
            }
        }

        // GET: API/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: API/Create
        [HttpPost]
        public ActionResult Create(APIView request)
        {
            try
            {
                bool isCreated = _apiService.CreateAPI(request);
                if (isCreated)
                    return RedirectToAction("Index");
                return View("Error");
            }
            catch (WebException ex)
            {
                _logger.Error(ex);
                var response = ex.Response as HttpWebResponse;
                if (response != null)
                {
                    if (response.StatusCode == HttpStatusCode.Unauthorized || response.StatusCode == HttpStatusCode.Forbidden)
                    {
                        return RedirectToAction("Logout", "Account");
                    }
                }
                return RedirectToAction("Logout", "Account");
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                return View("Error");
            }
        }

        // GET: API/Edit/5
        public ActionResult Edit(APIView request)
        {
            return View(request);
        }

        // POST: API/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, APIView request)
        {
            try
            {
                bool isUpdated = _apiService.UpdateAPI(id, request);
                if (isUpdated)
                    return RedirectToAction("Index");
                return View("Error");
            }
            catch (WebException ex)
            {
                _logger.Error(ex);
                var response = ex.Response as HttpWebResponse;
                if (response != null)
                {
                    if (response.StatusCode == HttpStatusCode.Unauthorized || response.StatusCode == HttpStatusCode.Forbidden)
                    {
                        return RedirectToAction("Logout", "Account");
                    }
                }
                return RedirectToAction("Logout", "Account");
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                return View("Error");
            }
        }

        // GET: API/Delete/5
        public ActionResult Delete(APIView request)
        {
            return View(request);
        }

        // POST: API/Delete/5
        //TODO:
        [HttpPost]
        public ActionResult Delete(int id, APIView request)
        {
            try
            {
                bool isDeleted = _apiService.DeleteAPI(request);
                if (isDeleted)
                    return RedirectToAction("Index");
                return View("Error");
            }
            catch (WebException ex)
            {
                _logger.Error(ex);
                var response = ex.Response as HttpWebResponse;
                if (response != null)
                {
                    if (response.StatusCode == HttpStatusCode.Unauthorized || response.StatusCode == HttpStatusCode.Forbidden)
                    {
                        return RedirectToAction("Logout", "Account");
                    }
                }
                return RedirectToAction("Logout", "Account");
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                return View("Error");
            }
        }

        //GET: API by UserType
        public ActionResult APIByUserType(int id, int? size)
        {
            try
            {
                List<APIView> listOfAPIByUserType = _apiService.ListOfAPIByUserType(id, size);
                ViewBag.id = id;
                return PartialView("_ListOfAPIByUserType", listOfAPIByUserType);
            }
            catch (WebException ex)
            {
                _logger.Error(ex);
                var response = ex.Response as HttpWebResponse;
                if (response != null)
                {
                    if (response.StatusCode == HttpStatusCode.Unauthorized || response.StatusCode == HttpStatusCode.Forbidden)
                    {
                        return RedirectToAction("Logout", "Account");
                    }
                }
                return RedirectToAction("Logout", "Account");
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                return View("Error");
            }
        }

        [HttpPost]
        public ActionResult LoadMoreAPIByUserType(int userTypeId, int? size)
        {
            try
            {
                List<APIView> listOfAPIByUserType = _apiService.ListOfAPIByUserType(userTypeId, size);
                ViewBag.id = userTypeId;
                if (listOfAPIByUserType != null)
                {
                    return PartialView("_LoadMoreAPIByUserType", listOfAPIByUserType);
                }
                return Json(listOfAPIByUserType);
            }
            catch (WebException ex)
            {
                _logger.Error(ex);
                var response = ex.Response as HttpWebResponse;
                if (response != null)
                {
                    if (response.StatusCode == HttpStatusCode.Unauthorized || response.StatusCode == HttpStatusCode.Forbidden)
                    {
                        return RedirectToAction("Logout", "Account");
                    }
                }
                return RedirectToAction("Logout", "Account");
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                return View("Error");
            }
        }
        //GET:
        public ActionResult ListAPINotInUserType(int? id)
        {
            try
            {
                List<APIView> apis = _apiService.ListAPINotInUserType(id);
                return Json(apis, JsonRequestBehavior.AllowGet);
            }
            catch (WebException ex)
            {
                _logger.Error(ex);
                var response = ex.Response as HttpWebResponse;
                if (response != null)
                {
                    if (response.StatusCode == HttpStatusCode.Unauthorized || response.StatusCode == HttpStatusCode.Forbidden)
                    {
                        return RedirectToAction("Logout", "Account");
                    }
                }
                return RedirectToAction("Logout", "Account");

WeDoShoesCMSAdminPanel/Controllers/FaqController.cs
using NLog;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WeDoShoesCMSAdminPanel.Filter;
using WeDoShoesCMSAdminPanel.Services;
using WeDoShoesCMSAdminPanel.ViewModel;

namespace WeDoShoesCMSAdminPanel.Controllers
{
    [AuthorizeFilter]
    public class FaqController : Controller
    {
        private readonly FaqService _faqService;
        private readonly Logger _logger;

        public FaqController()
        {
            _faqService = new FaqService();
            _logger = LogManager.GetCurrentClassLogger();
        }

        #region FaqCategory
        // GET: Faq Category List
        public ActionResult Index()
        {
            try
            {
                List<FaqCategoryView> listContactMode = _faqService.ListFaqCategory();
                return View(listContactMode);
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                return View("Error");
            }
        }

        // GET: Faq/CategoryDetails/5
        public ActionResult CategoryDetails(int id)
        {
            try
            {
                ViewData["categoryid"] = id;
                List<FaqView> listFaq = _faqService.ListFaqByCategoryId(id);
                return View("CategoryDetails",listFaq);
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                return View("Error");
            }
        }

        // GET: Faq/CreateCategory
        public ActionResult CreateCategory()
        {
            return View();
        }

        // POST: Faq/CreateCategory
        [HttpPost]
        public ActionResult CreateCategory(FaqCategoryView request)
        {
            if (!ModelState.IsValid)
                return View();
            try
            {
                bool isCreated = _faqService.CreateFaqCategory(request);
                if (isCreated)
                    return RedirectToAction("Index");
                return View("Error");
            }
            catch
            {
                return View("Error");
            }
        }

        // GET: Faq/Edit/5
        public ActionResult EditCategory(int id)
        {
            try
            {
                FaqCategoryView faqCategory = _faqService.FaqCategoryById(id);
                return View(faqCategory);
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                return View("Error");
            }
        }

        // POST: Faq/Edit/5
        [HttpPost]
        public ActionResult EditCategory(int id, FaqCategoryView request)
        {
            if (!ModelState.IsValid)
                return View(request);
            try
            {
                bool isUpdated = _faqService.UpdateFaqCategory(request);
                if (isUpdated)
                    return RedirectToAction("Index");
                return View("Error");
            }
            catch
            {
                return View("Error");
            }
        }

        // GET: Faq/Delete/5
        public ActionResult DeleteCategory(int id)
        {
            try
            {
                FaqCategoryView faqCategory = _faqService.FaqCategoryById(id);
                return View(faqCategory);
            }
            catch (Exception ex)
            {
                _logger.Error(ex);
                return View("Error");
            }
        }

        // POST: Faq/Delete/5
        [HttpPost]
        public ActionResult DeleteCategory(int id, FaqCategoryView request)
        {
            try
            {
                bool isDeleted = _faqService.DeleteFaqCategory(request);
                if (isDeleted)
                    return RedirectToAction("Index");
                return View("Error");
            }
            catch
            {
                return View("Error");
            }
        }
        #endregion

        #region Faq

        // GET: Faq/Create
        public ActionResult Create(int categoryId)
        {
            ViewData["categoryid"] = categoryId;
            return View();
        }

        // POST: Faq/Create
        [HttpPost]
        public ActionResult Create(FaqView request)
        {
            if (!ModelState.IsValid)
                return View();
            try
            {
                bool isCreated = _faqService.CreateFaq(request);
                if (isCreated)
                    return RedirectToAction("Index");
                return View("Error");
            }
            catch
            {
                return View("Error");
            }
        }

        // GET: Faq/Edit/5
        public ActionResult Edit(FaqView request)
        {
            return View(request);
        }

        // POST: Faq/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FaqView request)
        {
            if (!ModelState.IsValid)
                return View(request);
            try
            {
                bool isUpdated = _faqService.UpdateFaq(request);
                if (isUpdated)
                    return RedirectToAction("CategoryDetails", request.CategoryId);
                return View("Error");
            }
            catch
            {
                return View("Error");
            }
        }

        // GET: Faq/Delete/5
        public ActionResult Delete(FaqView request)
        {
            return View(request);
        }

        // POST: Faq/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FaqView request)
        {
            try
            {
                bool isDeleted = _faqService.DeleteFaq(request);
                if (isDeleted)
                    return RedirectToAction("Index");
                return View("Error");
            }
            catch
            {
                return View("Error");
            }
        }
        #endregion
    }
}

WeDoShoesCMSAdminPanel/Views/Shared/_AccessoryCostBySize.cshtml
@model WeDoShoesCMSAdminPanel.ViewModel.ProductView
<h4>Accessory And Labour Cost For Each Size</h4>
<hr />
@Html.ValidationSummary(true, "", new { @class = "text-danger" })
@for (int i = 0; i < Model.ServiceView.ListPriceView.Count; i++)
{
    @Html.HiddenFor(x => x.ServiceView.ListPriceView[i].ProductSizeType)
    <div class="form-group">
        @Html.LabelFor(x => x.ServiceView.ListPriceView[i].ProductSizeTypeName, "Size - " + Model.ServiceView.ListPriceView[i].ProductSizeTypeName, htmlAttributes: new { @class = "control-label col-md-4" })
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.ServiceView.ListPriceView[i].LabourCost, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(x => x.ServiceView.ListPriceView[i].LabourCost, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(x => x.ServiceView.ListPriceView[i].LabourCost, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.ServiceView.ListPriceView[i].AccessoryView.Id, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(x => x.ServiceView.ListPriceView[i].AccessoryView.Id, new SelectList(Model.ServiceView.PriceView.ListAccessoryView, "Id", "Name"), new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.ServiceView.ListPriceView[i].AccessoryView.Id, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.ServiceView.ListPriceView[i].Profit, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(x => x.ServiceView.ListPriceView[i].Profit, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(x => x.ServiceView.ListPriceView[i].Profit, "", new { @class = "text-danger" })
        </div>
    </div>
}

WeDoShoesCMSAdminPanel/Views/Shared/_AppendSubService.cshtml
@model WeDoShoesCMSAdminPanel.ViewModel.SubServiceView
@using HtmlHelpers.BeginCollectionItem

@using (Html.BeginCollectionItem("ListSubServiceView")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal" id="@Model.UniqueID">
       
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Acronym, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Acronym, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Acronym, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.ParentId)
        @Html.HiddenFor(model => model.CategoryId)
        @Html.HiddenFor(model => model.Type)
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                
                    <input type="button" value="Remove" id="cancel" name="Cancel" onclick="deleteAddress(document.getElementById('@Model.UniqueID'));"/>
               
            </div>
            
    </div>
        </div>
}

WeDoShoesCMSAdminPanel/Views/Shared/_BrandsByProduct.cshtml
@model IEnumerable<WeDoShoesCMSAdminPanel.ViewModel.BrandsView>

<div>
    <h4>Added Brands</h4>
    <hr />

    <div style="display:inline-block">
        
        <dl class="dl-horizontal" style="position:page">           
            @if (Model != null)
            {           
                int i = 0;
                foreach (var item in Model)
                {
                    i++;                    
                    <div class="form-horizontal" style="display:inline-block;padding-right:inherit ;position:page;margin-right:50px">                      
                        <dt>
                            @Html.DisplayFor(modelItem => item.Name)
                        </dt>
                        <dd>
                            @Html.ActionLink("Remove", "RemoveBrand", new { id = item.Id, productId = ViewData["productid"] }, new { onclick = "return confirm('Are you sure you wish to remove this brand?');" })
                        </dd>                                       
                    </div>
                    if (i % 2 == 0)
                    {
                        <br/>
                    }
                }              
            }           
            @*<dt>
                @Html.ActionLink("Add Brand", "BrandsNotInProduct", new { productId = ViewData["productid"], categoryId = ViewData["categoryid"] })
            </dt>*@
            </dl>
        <div />
            @*<br/>*@
        </div>
<p>
    @Html.ActionLink("Add Brand", "BrandsNotInProduct", new { productId = ViewData["productid"], categoryId = ViewData["categoryid"] })
</p>

WeDoShoesCMSAdminPanel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title WeDoShoes CMS</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("WeDoShoes CMS", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (HttpContext.Current.Session["token"] != null)
                    {
                        <li>@Html.ActionLink("Categories", "Index", "Category")</li>
                        <li>@Html.ActionLink("Services", "Index", "Service")</li>
                        <li>@Html.ActionLink("Products", "Index", "Product")</li>
                        <li>@Html.ActionLink("Accessories", "Index", "Accessories")</li>
                        <li>@Html.ActionLink("Brands", "Index", "Brands")</li>
                        <li>@Html.ActionLink("Sizes", "Index", "SizeType")</li>
                        <li class="dropdown">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown">More<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Contact Mode", "Index", "ContactMode")</li>
                                <li>@Html.ActionLink("Defect", "Index", "Defect")</li>
                                <li>@Html.ActionLink("FAQ Category", "Index", "Faq")</li>
                                <li>@Html.ActionLink("Nation State", "Index", "NationState")</li>
                                <li>@Html.ActionLink("Tax", "Index", "Tax")</li>
                                <li>@Html.ActionLink("Manage Time Slot", "Index", "TimeSlot")</li>
                                <li>@Html.ActionLink("Manage User Type", "Index", "UserType")</li>
                                <li>@Html.ActionLink("Manage API", "Index", "API")</li>                           
                            </ul>
                        </li>
                        <li>@Html.ActionLink("Welcome " + HttpContext.Current.Session["name"].ToString().Split(' ').FirstOrDefault(), "Index", "Home")</li>
                        <li>@Html.ActionLink("Logout", "Logout", "Account")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - WeDoShoes</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WeDoShoesCMSAdminPanel/Views/Shared/_ListOfAPIByUserType.cshtml
@model IEnumerable<WeDoShoesCMSAdminPanel.ViewModel.APIView>
<hr/>
<h4>List Of Permitted APIS</h4>

<p>
    @Html.ActionLink("Add New Permission", "AddAPI", new { id = ViewBag.id })
</p>
<table class="table" id="APITable">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DisplayName)
        </th>
        <th>
            Action
        </th>
        <th></th>
    </tr>

    @if (Model != null)
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DisplayName)
                </td>
                <td>
                    @Html.ActionLink("Revoke Permission", "RevokeAPIPermission", new { userTypeId = ViewBag.id, apiId = item.Id }, new { onclick = "return confirm('Are you sure you wish to revok permission for this API?');" })
                </td>
            </tr>
        }
    }
</table>
@if (Model != null)
{
    if (Model.Count() >= 20)
    {
        <p id="loadMore" style="text-align: center;">
            <a class="btn btn-default">
                Load More@*&raquo;*@
                <span>
                    <img id="loading" style="display: none;" src="~/Content/Images/ajax-loader.gif" />
                </span>
            </a>
        </p>
    }
}

WeDoShoesCMSAdminPanel/Views/Shared/_ListUserTypeByAPI.cshtml
@model IEnumerable<WeDoShoesCMSAdminPanel.ViewModel.UserTypeView>
<hr/>
<h4>List Of Permitted User Type</h4>

<p>
    @Html.ActionLink("Add New Permission", "AddUserType", new { id = ViewBag.id})
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            Action
        </th>
        <th></th>
    </tr>

    @if (Model != null)
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.ActionLink("Revoke Permission", "RevokeUserPermission", new { userTypeId = item.Id, apiId = ViewBag.id }, new { onclick = "return confirm('Are you sure you wish to revok permission for this User Type?');" })
                </td>
            </tr>
        }
    }
</table>

WeDoShoesCMSAdminPanel/Views/Shared/_LoadMoreAPIByUserType.cshtml
@model IEnumerable<WeDoShoesCMSAdminPanel.ViewModel.APIView>
@foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DisplayName)
            </td>
            <td>
                @Html.ActionLink("Revoke Permission", "RevokeAPIPermission", new { userTypeId = ViewBag.id, apiId = item.Id }, new { onclick = "return confirm('Are you sure you wish to revok permission for this API?');" })
            </td>
        </tr>
    }

WeDoShoesCMSAdminPanel/Views/Shared/_LoadMoreAccessory.cshtml
@model IEnumerable<WeDoShoesCMSAdminPanel.ViewModel.AccessoryView>


@if (Model != null)
{
    foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.Id })
            </td>
        </tr>
    }
}

WeDoShoesCMSAdminPanel/Views/Shared/_MaterialCostBySize.cshtml
@model WeDoShoesCMSAdminPanel.ViewModel.ProductView
<h4>Material And Labour Cost For Each Size</h4>
<hr />
@Html.ValidationSummary(true, "", new { @class = "text-danger" })
@for (int i = 0; i < Model.ServiceView.ListPriceView.Count; i++)
{
    @Html.HiddenFor(x => x.ServiceView.ListPriceView[i].ProductSizeType)
    <div class="form-group">
        @Html.LabelFor(x => x.ServiceView.ListPriceView[i].ProductSizeTypeName, "Size - " + Model.ServiceView.ListPriceView[i].ProductSizeTypeName, htmlAttributes: new { @class = "control-label col-md-4" })
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.ServiceView.ListPriceView[i].LabourCost, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(x => x.ServiceView.ListPriceView[i].LabourCost, new { htmlAttributes = new { @class = "form-control", required = "required" } })
            @Html.ValidationMessageFor(x => x.ServiceView.ListPriceView[i].LabourCost,"", new { @class = "text-danger"})
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.ServiceView.ListPriceView[i].MaterialCost, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(x => x.ServiceView.ListPriceView[i].MaterialCost, new { htmlAttributes = new { @class = "form-control", required = "required"} })
            @Html.ValidationMessageFor(x => x.ServiceView.ListPriceView[i].MaterialCost, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(x => x.ServiceView.ListPriceView[i].Profit, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(x => x.ServiceView.ListPriceView[i].Profit, new { htmlAttributes = new { @class = "form-control", required = "required" } })
            @Html.ValidationMessageFor(x => x.ServiceView.ListPriceView[i].Profit, "", new { @class = "text-danger"})
        </div>
    </div>
}